on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

name: Test

jobs:
  alejandra:
    runs-on: namespace-profile-ghostty-sm
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4 # Check out repo so we can lint it
      - name: Setup Cache
        uses: namespacelabs/nscloud-cache-action@v1.2.0
        with:
          path: |
            /nix
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: alejandra check
        run: nix develop -c alejandra --check .

  prettier:
    runs-on: namespace-profile-ghostty-sm
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4 # Check out repo so we can lint it
      - name: Setup Cache
        uses: namespacelabs/nscloud-cache-action@v1.2.0
        with:
          path: |
            /nix
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: prettier check
        run: nix develop -c prettier --check .
